### ISSUE TITLE
Add support for public fields instead of getters

### ISSUE THREAD

**Issue by mswiderski** [smallrye/smallrye-graphql#1026]
When using beans that are returned from GraphQL services that use only public fields instead of java bean approach (getters/setters) then there is a DataFetchException returned for every path that targets beans without getters and setters.

Would be really good to have support for beans with public fields as this becomes more and more common.

Unless I missed some sort of configuration that enables that.

Using smallrye-graphql version 1.3.1 through quarkus 2.2.1

**Comment by phillip-kruger** [comment]
Are these also panache entities ? If so, there was a bug w.r.t that, that is now fixed (https://github.com/quarkusio/quarkus/pull/19883). If not, then there is a issue, as we do support public fields.

**Comment by mswiderski** [comment]
yes, indeed it is panache entity. so I guess it's good to be closed as 2.3 of quarkus will come with the fix. thanks @phillip-kruger

**Comment by phillip-kruger** [comment]
Great ! Closing here then

**Comment by phillip-kruger** [comment]
For your interest: When a panache bean builds, all fields are changed to protected, and getters/setters are added. So the issue was that GraphQL build a model, that wants to execute using the field, but then on runtime the fields are not accessible. So the fix was to update the Jandex index with the modified panache entities, before building the GraphQL mode.
