### ISSUE TITLE
See why JDK8 is not building anymore in Github actions

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#103]
We suddenly get this error w.r.t JBoss Logger on JDK8 in GitHub Actions.

**Comment by radcortez** [comment]
In the TCK, Wildfly tries to download the graphql artifacts from the Maven repo. They are not there, because the command only runs `verify`. When running with `install` it works properly.

Now, I don't have any idea why this works with JDK 11 and just `verify`, because it seems to do the same thing, but actually works in the end.

**Comment by radcortez** [comment]
This https://github.com/smallrye/smallrye-graphql/pull/109 fixed it.
