### ISSUE TITLE
Support for jersey

### ISSUE THREAD

**Issue by vamshikrishnamraju** [smallrye/smallrye-graphql#1079]
Hi,

Currently we are using Jersey and I don't see any support for jersey in the current libraries. Is there a roadmap for this ?

Thanks

**Comment by jmartisk** [comment]
What exactly do you mean by supporting Jersey? Jersey is a JAX-RS implementation, we don't depend on JAX-RS.
The typesafe client library used to depend on a JAX-RS Client implementation, but that's not true anymore - it uses Vert.x Web client now.

**Comment by vamshikrishnamraju** [comment]
In our project we use jersey/jaxrs and I am not able to register the servlets of smallrye graphql. So I was wondering whether there is any other implementation to microprofile graphql which supports jaxrs.

**Comment by phillip-kruger** [comment]
There is no need for JAX-RS on the server if you want to use GraphQL. But, if you really want to you can hook this up yourself. Basically create a new JAX-RS Endpoint that accepts POST requests on /graphql and then use smallrye-graphql to execute the result. So have a look at the servlet module in here, and convert that to jaxrs. If you are using Wildfly, OpenLiberty or Quarkus, you can just include smallrye-graphql extension.

**Comment by jmartisk** [comment]
Yeah, you might want to either "copy" the servlets and transform into JAX-RS endpoints (it shouldn't be super difficult)... or maybe add a servlet container into your project and use the servlets directly?

**Comment by vamshikrishnamraju** [comment]
I tried that but the listener and servlet classes are dependent on other applicationscoped classes because if which I am getting NPE

**Comment by jmartisk** [comment]
Then your CDI environment is probably not set up properly to discover the beans?! Switching to JAX-RS instead of servlets wouldn't help, you would still need CDI as well.
The `ExecutionService` class is not a CDI bean by itself, but is produced by https://github.com/smallrye/smallrye-graphql/blob/1.3.4/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/producer/GraphQLProducer.java - perhaps you don't have the `implementation-cdi` module included, or something.
