### ISSUE TITLE
Too many open files exception via VertxTypesafeGraphQLClientBuilder

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#1099]
When I run larger test suites (also the typesafe client TCK) that use the `VertxTypesafeGraphQLClientBuilder` in InttelliJ on a Mac, I eventually get a `java.io.IOException: Too many open files`. It happens from within [this call to `Vertx.vertx()`](https://github.com/smallrye/smallrye-graphql/blob/bc8415788e7e8c693e678aebbdf7b8df520e6b69/client/implementation-vertx/src/main/java/io/smallrye/graphql/client/typesafe/vertx/VertxTypesafeGraphQLClientBuilder.java#L55), I assume because the `Vertx` instance is never being closed. I assume that this could be an issue in other scenarios, too, but haven't experienced it, yet. And I assume that it's not so easy to fix, as the proxy probably still requires the instance to be open to make actual calls.

**Comment by t1** [comment]
Just a side note: my IDE hinted me that the `Vertx` field in the `VertxTypesafeGraphQLClientProxy` is never used and could be removed. And I think that the complete `WebClient` building logic could be moved into the builder, so it's not distributed over two classes.

**Comment by t1** [comment]
Another thought: could it be sufficient to have a singleton default `Vertx` instance in the builder?

**Comment by jmartisk** [comment]
I'm not completely sure about storing the created Vertx instance in a static field - static fields are shared between deployments in multi-app environments like WildFly, because the library will be loaded by the same class loader for all deployments that use it. So this way, in WildFly, if you create one Vert.x instance, all deployments will use the same one from then on. I believe each deployment should have its own separate Vert.x instance?!  

AFAIK WildFly does not manage a Vert.x instance by itself (which means `Vertx.currentContext()` will be null)

Perhaps @kabir can help - do you think we should manage a separate Vert.x instance per deployment? And if yes, how best to do that - turn the static field into a map keyed by the TCCL to identify a deployment? Or, should some logic for creating a Vertx instance be present in the `microprofile-graphql-smallrye` subsystem, creating it during deployment time in a way that smallrye can later obtain it through calling `Vertx.currentContext()`? Are there plans in WF for this to be managed automatically by any subsystem?

**Comment by jmartisk** [comment]
Sorry, this comment would have been more appropriate on the PR itself rather than here, I'll re-post it there

**Comment by jmartisk** [comment]
This was resolved via https://github.com/smallrye/smallrye-graphql/pull/1101
