### ISSUE TITLE
Thorntail to Wildfly in the TCK

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#127]
Change the TCK to use Wildfly (rather than Thorntail)

It kind of work if you uncomment the pom profile (and comment out the thorntail part) however it only run 1 of the 2 TCK tests when using Wildfly.

There are 2 tests (so the server needs to start twice). 
1) Validation against the schema (Thorntail and Wildfly works)
2) Test some executions (Thorntail work, Wildfly does not pick up this test ??)

**Comment by phillip-kruger** [comment]
@jmartisk - would you know why this is happening ?

**Comment by jmartisk** [comment]
I'll have a look today, this is weird

**Comment by phillip-kruger** [comment]
Thanks @jmartisk !

**Comment by jmartisk** [comment]
Aaargh, after nearly crushing my skull not knowing why the hell `ExecutionDynamicTest` is getting ignored, I finally know. TestNG ignores that test because after switching to Thorntail container, there is a missing required dependency on `org.glassfish:jakarta.json` so loading the test class fails. Wonder why TestNG does not log anything but silently ignores it instead.  Dammit.
