### ISSUE TITLE
Allow Locale for validation

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#1320]
(and in general)

Currently, setting the Local.default has no effect on validation messages.

1) I think we need to fix that.
2) We probably need to add locale to the context, and if set in the HTTP layer (header and query parameter ?), and different than default, change it automatically.

cc @jmartisk w.d.y.t ?

f.y.i @raoua-eng

**Comment by raoua-eng** [comment]
Thanks for creating the issue.
I want to add that when we add the ```quarkus.default-locale=iso_language``` internationalization works well for error message validation.

**Comment by raoua-eng** [comment]
Hello @jmartisk, 
I mean when I specify the quarkus property ```quarkus.default-locale=fr``` in application.properties file, i18n for validation error works well.

For me I created an interceptor to be invoked for every mutation, and that interceptor changes the locale iso language by the language given from a jwt, as I see the locale is changed but the error validation message for that particular language is not returned yet.

**Comment by jmartisk** [comment]
I am working on a solution where messages will be in the language specified in the `Accept-Language` header and will soon have a pull request to Quarkus.

You're saying that you also want it to consider the language inside a JWT token? That might be possible, I don't think any Quarkus extensions do anything like that at the moment though (probably not even RESTEasy).

**Comment by jmartisk** [comment]
The solution I mentioned earlier is now merged in the Quarkus repo, it will be in Quarkus 2.9.0 and 2.8.1 I think.
If we want it to work with JWT tokens, this should probably be filed as a new issue in the Quarkus repo, because we would probably also need to do this for JAX-RS endpoints, not just GraphQL.

**Comment by raoua-eng** [comment]
Thanks Jan, That's sounds great !
To specify the language in the ```Accept-Language``` header is a great solution. Another way to do this (rather than interceptor) is to use events. As I see, It's similar to interceptor, we have to inject the token and call the ```Locale.setDefault()```. So if the way with the interceptor is solved, the same with events.

Yes I want to consider the token's language. But we use a custom token, I don't think it is feasable ?

**Comment by jmartisk** [comment]
Hm yea I think your case is getting a bit too specific. 
I have a rough idea that could get it working for you, it's not very straightforward, but I *think* it could work:

- Create and register (in META-INF/services) your own implementation of `io.smallrye.graphql.spi.ValidationService` that  does pretty much the same as `io.smallrye.graphql.cdi.validation.ValidationService`,
- except that it doesn't obtain the `ValidatorFactory` by injecting the default one, but instead builds its own by doing something like `Validation.byProvider(HibernateValidator.class).configure().localeResolver(YOUR_RESOLVER).buildValidatorFactory();`
- where `YOUR_RESOLVER` is an implementation of `LocaleResolver` whose `resolve` method uses CDI to obtain the current JWT token, retrieves the locale from it and returns it

**Comment by raoua-eng** [comment]
Thanks a lot, I'll give this a try!
