### ISSUE TITLE
error handling in case of 4xx response from server

### ISSUE THREAD

**Issue by maxandersen** [smallrye/smallrye-graphql#1402]
today when client requests from a server (i.e. github.com) that returns 403 when your token is incorrect or missing in header 
graphql client returns empty document with no errors.

https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#client-is-not-allowed-to-access-the-schema states servers should return 4xx when no access - thus I would say the client should react differently than returning a doc which is empty and no errors.

throw an exception or add some error info ?

**Comment by jmartisk** [comment]
My opinion is that we should not look that much into the HTTP response code, but rather see whether the response body actually contains a valid GraphQL response, because even if there's a crazy response code, there might be a proper response with it.

- If there's a GraphQL response that can be parsed (even if it potentially has no data, just errors), just try to treat it as a normal GraphQL response.
  - For dynamic clients, this would mean potentially empty `getData()`, but no exception. You would be able to retrieve the code and message programmatically.
  - For typesafe clients, this would still potentially mean an exception, if we're unable to build an instance of the requested response class.
- If there is no such GraphQL response, always throw an exception whose message contains the HTTP response code and the body (if we received any).

Another matter is how to define what we consider a proper GraphQL response in the body. I think that would mean a well-formed JSON document that, at the root level, contains at least one of the entries `errors`, `data` and `extensions`, and **no other** entries. This is in line with the graphql spec (https://spec.graphql.org/draft/#sec-Response-Format) that says

> To ensure future changes to the protocol do not break existing servers and clients, the top level response map must not contain any entries other than the three described above.

Regarding your GitHub case, a request without authentication returns a document that contains `message` and `documentation_url` keys, so that would be treated with an exception, because that's not a proper GraphQL response.
Does this sound reasonable?

**Comment by maxandersen** [comment]
So you are suggestion to do the same with the type safe client ? 


Looking at how jaxrs do it I can get object/json/etc. No matter the status code but Afaics we are missing that basic ability in the graphql client. hasErrors() just seem to care about the graphql layer. 

Is there a hasTransportErrors() or getTransportStatus() hidden somewhere to reliably use ?

**Comment by jmartisk** [comment]
> So you are suggestion to do the same with the type safe client ?
> 

The problem with typesafe clients is that when we return a domain object, it's not easy to attach the response metadata to it. For that, we would have to either
- make the returned object some sort of proxy where you would be able to call something like `ResponseMetadata.get(proxy)` on it to get the response code etc
- or add an interface, for example `TypesafeResponse<T>` where `<T>` is the actual domain object, and allow the client API to request `TypesafeResponse<T>` instead of `<T>` directly, and the wrapper would allow to retrieve the metadata

But neither of this is very convenient IMO... That would need some consideration whether it's really needed to have.


> Looking at how jaxrs do it I can get object/json/etc. No matter the status code but Afaics we are missing that basic ability in the graphql client. 
> hasErrors() just seem to care about the graphql layer.

Per my suggestion, if we return a `Response` object only with a proper GraphQL response, then it means there are no errors on other layers, apart from potentially a weird status code/message, but you can retrieve that.
We also have a shortcut method `ResponseImpl.throwExceptionIfErrors()` that attempts to convert the GraphQL-level errors to a `GraphQLClientException` and throws it, if there are any.

> 
> Is there a hasTransportErrors() or getTransportStatus() hidden somewhere to reliably use ?

`ResponseImpl` has recently received `getStatusCode()` and `getStatusMessage()`, and it can also be obtained from the map returned by `Response.getTransportMeta()` if you don't want to cast to `ResponseImpl`
