### ISSUE TITLE
Client with Nested Queries

### ISSUE THREAD

**Issue by bollerdominik** [smallrye/smallrye-graphql#1926]
I want to do following query in a `smallrye.graphql.client`

```graphql
query {
  terminal(key: "ABCEDF") {
    request(key: "EFGHJK") {
      state
    }
  }
}

```
I tried

```java
 @Query("terminal")
 PaymentRequestType getTerminalPayment(@Name("key") String terminalKey, @NestedParameter("request") @Name("key") String key);
```

Howver, this does not produce the right result. It is not clear how I can achieve this. Is this supported with  `smallrye.graphql.client`?  Any advice is much appreciated.

**Comment by t1** [comment]
The issue is probably related to the two variables called `key`. I've tried to reproduce your issue, but it works for me:

```java
    @GraphQLClientApi
    interface TerminalsApi {
        Terminal terminal(@Name("key") String terminalKey, @NestedParameter("request") @Name("key") String requestKey);
    }

    class Terminal {
        List<Request> request;
    }

    class Request {
        String state;
    }

    Terminal terminal = api.terminal("ABCDEF", "GHIJKL");
```

This produces a query `query terminal($terminalKey: String, $requestKey: String) { terminal(key: $terminalKey) 
{request(key: $requestKey) {state}}}` and the variables `{'terminalKey':'ABCDEF','requestKey':'GHIJKL'}`.

It _could_ be that you don't have the `-parameters` compiler option set, so it can't distinguish between the two `key` parameters. If that's not the case, do you have a reproducer? If it is, maybe you could suggest, how this could be documented more clearly... maybe even with a more specific error message.

**Comment by bollerdominik** [comment]
Seems to be my mistake. My response object simply had the `String state` field. I did not wrap it in a separate Request object like you did. Now it works. Thanks for your support. Much appreciated.
