### ISSUE TITLE
Typesafe ErrorOr do not handle QueryDidNotValidate error

### ISSUE THREAD

**Issue by ITrium-Salah** [smallrye/smallrye-graphql#2078]
When using ErrorOr<Data> myMutation(args....) we expect that all server side errors are wrapped in the ErrorOr object.
Unfortunately the GraphQlClientException seem not be wrapped. When sending a mutation with bad parameter input type the backend log QueryDidNotValidate and the client fail.

We expect the exception to be wrapped in the ErrorOr

**Comment by t1** [comment]
This looks a bit esoteric to me: why would you regularly send invalid input?

Nonetheless, without looking at the code, I assume that the problem is, that the result doesn't contain a `location` for the result field where the error could be attached to.

**Comment by jmartisk** [comment]
There's a difference between a problem during data fetching (server returns an error for a specific field, and that error gets deserialized into a `GraphQLError` instance and wrapped into an `ErrorOr`) and a problem with executing the operation as a whole. In the latter case, we can't wrap it into a `GraphQLError` because the problem might be something completely arbitrary, like a `connection refused` etc.
An `ErrorOr` needs to contain a reference to a `GraphQLError`, which is something specific to GraphQL data fetching problems - if you look at the code (https://github.com/smallrye/smallrye-graphql/blob/2.8.1/client/api/src/main/java/io/smallrye/graphql/client/GraphQLError.java) you see this is unsuitable for capturing other types of errors. Yeah, as t1 said, without a specific `location`, we can't create an `ErrorOr`, so I think this should be considered correct behavior...

**Comment by ITrium-Salah** [comment]
Thank you for your response, i close the issue
