### ISSUE TITLE
Allow using @Named on @GraphQLApi resource

### ISSUE THREAD

**Issue by mejlholm** [smallrye/smallrye-graphql#426]
Hi,

following discussion with @phillip-kruger in Quarkus issue https://github.com/quarkusio/quarkus/issues/12302, we agreed to create a seperate issue here. 

Basically, we are concerned with how the maintainability of the code scales as the number of graphql endpoints grow. It would be nice to have an equivalent to @Path in JAX-RS, but that is a change to the microprofile spec, which I've also created an issue on here: 
https://github.com/eclipse/microprofile-graphql/issues/320

If the spec cannot be changed or the issue is rejected, then we would like to test out the following addition to the @GraphQLApi annotation:

`@GraphQLApi @Name("Books")`

**Comment by phillip-kruger** [comment]
@mejlholm - I started looking at this. THe top-level grouping can not be the same for mutations and queries. (They have to have unique names) - so we can do something like this, if you annotate with `@Name("books") the Mutation becomes `booksInput`.
Or we can do something like, for queries if becomes `booksQuery` and for mutation it becomes `booksMutation`.

w.d.y.t ? 

@andymc12 @kaqqao - any thoughts ?

**Comment by phillip-kruger** [comment]
@mejlholm - ignore the above. It should be possible. I must be doing something else wrong...

**Comment by phillip-kruger** [comment]
@mejlholm - Right, so the field name can be the same, so you can do:

```
query{
  books{
    allBooks{
      isbn
      published
      title
      authors
    }
  }
}
```
and 

```
mutation{
  books{
    addBook(book:{
          isbn: "0-571-05686-5"
          published: "1954-09-17"
          title: "Lord of the Flies"
          authors: "William Golding"
        }
    ){
      isbn
      published
      title
      authors
    }
  }
}
```
both using books, that now comes from:

```
@GraphQLApi
@Name("books")
@Description("Allow all book releated APIs")
public class BookGraphQLApi {

    @Query
    public List<Book> getAllBooks() {
        return new ArrayList<>(BOOKS.values());
    }

    @Query
    public Book getBook(String name) {
        return BOOKS.get(name);
    }

    @Mutation
    public Book addBook(Book book) {
        BOOKS.put(book.title, book);
        return book;
    }
```

However, books is not a real type in Java, as it's just a grouping of queries, so in the Schema the 'return' for that is `booksQuery` and `booksMutation` (the type name needs to be unique).

I'll discuss this in today's meeting in the spec, and then do a PR

**Comment by phillip-kruger** [comment]
![Peek 2020-09-30 10-00](https://user-images.githubusercontent.com/6836179/94659055-fe3b0c80-0303-11eb-854c-cb62dda20b1a.gif)

**Comment by mejlholm** [comment]
Looks good, I'll have a look at the PR as well.

**Comment by kaqqao** [comment]
@phillip-kruger Don't get mad for me taking this long to chip in, but the "grouped mutations" are no longer mutations as per GraphQL semantics.

E.g. in

```graphql
mutation {
   books {
      addBook {...}
   }
}
```

`addBook` is _not_ a mutation, but a query with incidental side-effects. And since GraphQL execution semantics are specified differently for mutations and queries, this creates a dangerous and very subtle land mine. I wrote at length about this [here](https://www.reddit.com/r/graphql/comments/fegxrp/organizing_queries_in_top_level_groups_pro_con/fjvru00?utm_source=share&utm_medium=web2x&context=3) (better if you follow the entire thread). In short - all mutations (and subscriptions) are top-level operations, and can not be grouped (except by naming conventions).

With this in mind, this proposal is only valid for queries. Which in itself is fine, but creates a rather strange asymmetry with other operations.
