### ISSUE TITLE
resteasy-client Dependency required since 1.0.10

### ISSUE THREAD

**Issue by Alwaysgone** [smallrye/smallrye-graphql#428]
Since Version 1.0.10 the resteasy-client dependency is a required dependency for smallrye-graphql-client. This change seems to be introduced by commit 6e1899ab7057db6d88e22c84acb05e39733a4d2d, where the dependency management of resteasy-client switched from scope test to scope compile. If this happened accidently it would be nice to change it back because our services use jersey as jaxrs clients. Since resteasy-clients do not support constructor injection it woud either force us to make all classes injectable with field injection only for it to work or exclude resteasy-clients everywhere graphql is used.
Our current workaround is to exclude resteasy-client explictly when adding it as a dependency.

		<dependency>
			<groupId>io.smallrye</groupId>
			<artifactId>smallrye-graphql-client</artifactId>
			<version>${smallrye-graphql.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.resteasy</groupId>
					<artifactId>resteasy-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by jmartisk** [comment]
This was surely not accidental, we did that change because we wanted to have the `smallrye-graphql-client` artifact contain all dependencies that it needs at runtime. At first I was thinking of introducing a new separate Maven artifact for that, but then after discussing with @phillip-kruger  (https://github.com/smallrye/smallrye-graphql/pull/409#pullrequestreview-491418635) I did that change in the `smallrye-graphql-client` itself. 

So we basically have these choices now:
- Argue whether Resteasy or Jersey is a better choice  and potentially switch to Jersey by default (but most downstream consumers of SR GraphQL, I assume, use Resteasy rather than Jersey)
- Go with the "two separate artifacts" approach after all, where there is a core client artifact without runtime-only dependencies, and a separate all-in-one artifact which does include them
- Remove the Resteasy dependency and require the users to add a JAX-RS client dependency explicitly, but that violates what we wanted to achieve with an all-in-one artifact
- Just keep it as is and let users exclude Resteasy if they want to use Jersey (my preferred approach right now, but I could be convinced otherwise)

**Comment by phillip-kruger** [comment]
A, ok now I follow. Apologies, this is my fault. Yes maybe we should revert that. And create a new module (like you had it). Although I would call it client-standalone (and not client-all).
w.d.y.t ?
@jmartisk ?

**Comment by jmartisk** [comment]
After talking to Phillip privately, we decided to go with reverting the original commit and adding a new separate module with artifactID `smallrye-graphql-client-all`
I'll prepare a PR soon

**Comment by Alwaysgone** [comment]
Cheers, thank you very much for the explanation. We'll switch to 1.0.12 as soon as it's released. Thank you and have a nice day.

**Comment by andymc12** [comment]
Sorry for coming late to this party, but at one point weren't we thinking of replacing the underlying transport with something like Apache HTTP Client?  In general, RESTEasy or Jersey are probably a bit more overweight for a non-RESTful client implementation.

**Comment by jmartisk** [comment]
The thing is we actually are using it as a JAX-RS client right now. Switching to pure HTTP is possible, but we would have to remove all `javax.ws.rs` api usage. Maybe we could file a separate issue to get it done at some point?

**Comment by phillip-kruger** [comment]
Agree, lets create a separate issue.

**Comment by jmartisk** [comment]
ok, created https://github.com/smallrye/smallrye-graphql/issues/436

**Comment by phillip-kruger** [comment]
@Alwaysgone - 1.0.12 is released and is back to not including the resteasy dependency
