### ISSUE TITLE
Support for multiple queries in same request (Client)

### ISSUE THREAD

**Issue by daniel-chelcioiu** [smallrye/smallrye-graphql#627]
Is there a possibility to make multiple queries in same request ? 
Example: 
`{
    findHero(id: 1) {
         name
    }
    findVillain(id: 2) {
        name
    }
}`

In this case there are 2 queries that are made in the same http request. Is this possible with current client API ? 

P.S. This is a great API, great work. :)

**Comment by phillip-kruger** [comment]
@t1 ^^^

**Comment by jmartisk** [comment]
With how the client is designed now (client is basically a proxy object where each method corresponds to a query) it's a bit hard for me to imagine how that would work - how we would "join" two queries - two method calls - together into one. 
We could do this by supporting adding some special new methods to the relevant `@GraphQlClientApi` interface, but it's not clear what the return type should be, if the call returns data from multiple queries. 

I think that rather than proxies + annotated interfaces, we would need a DSL with some generic classes representing queries and responses, similar to `javax.ws.rs.client.Entity`, `javax.ws.rs.core.Response`, etc. This API would be able to handle multiple queries in one, and also dynamically choosing which fields to retrieve, etc.

@t1 are there any plans to introduce something like this? I think it could be complementary to the current approach. If people agree it's a good idea and no one is working on it, I would volunteer for trying to design it.

**Comment by jmartisk** [comment]
After talking to @phillip-kruger it seems I missed how there is already some draft API in the spec repository and SmallRye doesn't support it yet, so I think I'll need to look into that

**Comment by jmartisk** [comment]
I filed https://github.com/smallrye/smallrye-graphql/issues/635 - this should cover it once implemented.

**Comment by t1** [comment]
Just a raw thought: we now have nested params (#465); maybe an alternative could be to use a wrapper return type, i.e.

```java
@GraphQlClientApi
interface API {
    HeroAndVillain findHeroAndVillain(@NestedParameter("hero") int heroId, @NestedParameter("villain") int villainId);
}

class HeroAndVillain {
    Hero hero;
    Villain villain;
}
```

This already produces:

```graphql
query findHeroAndVillain($heroId: Int!, $villainId: Int!) {
    findHeroAndVillain() {
        hero(heroId: $heroId) {name}
        villain(villainId: $villainId) {name}
    }
}
```

We could create a new annotation like `@Unwrap` on the method, to get rid of the `findHeroAndVillain()` field in the query. Would that be too much magic? Any better name for this annotation?

**Comment by t1** [comment]
Fixed!

I found `@Multi` more descriptive than `@Unwrap`. Do you agree?
