### ISSUE TITLE
Indexer doesn't work in JDK11 or with Wildfly

### ISSUE THREAD

**Issue by ribizli** [smallrye/smallrye-graphql#64]
I tried to integrate this lib into my Wildfly JakartaEE project, but the indexer couldn't find my annotated `@GraphQLApi` classes.

The (open)JDK11 case is reproducible with the example project (https://github.com/phillip-kruger/graphql-example) too.

In Wildfly I've debugged the classpath resolution logic, and found, that only the `jboss-modules.jar` is processed by the indexer.

The only successful execution was with JDK8 and Thorntail.

**Comment by phillip-kruger** [comment]
Thanks. I'll look at this a.s.a.p

**Comment by jmartisk** [comment]
Perhaps including a pre-computed `META-INF/jandex.idx` in the deployment could solve this, but yeah we should probably make sure that the dynamic index computation works with wildfly too

**Comment by ribizli** [comment]
@jmartisk I've tried that too, problem was: `getClass().getResourceAsStream(...)` still not correct, because it looks in the lib not in the war...

**Comment by phillip-kruger** [comment]
@ribizli - You are welcome to fix it and do a PR :) We also need to add test cases that simulate all the scenarios. 
Also (hopefully) soon this will just be part of Wildfly and you would not have to add this lib to your project.

**Comment by phillip-kruger** [comment]
Partially fixed (or at least a workaround) in PR #65. But we keep this open to do a propper fix where we scan the classpath (for jars) and the war or do the scanning in the war.

**Comment by t1** [comment]
The Jandex workaround helps a bit, but when I add a `@Source` method, the `ReflectionDataFetcher` fails with a NPE, because the `methodInfo.declaringClass()` is `null`. Is this a separate bug or even a problem with Jandex?

I suppose fixing this issue #64 would also fix this problem. It seems to be non-trivial, but can I support somehow?

**Comment by phillip-kruger** [comment]
So the fix for JDK 11 happened mostly in the MP Spec TCK. I think there is a bigger issue here with JDK 11 in Runtime. Once Spec 1.0.1 is released (soon) we should be able to at least build against JDK 11 and pass all tests. Then we can investigate why normal running is not working (I know the runner does not work in JDK 11).

**Comment by phillip-kruger** [comment]
One of the things I want to do soon is "removing" Jandex and have an internal model. That would allow Quarkus to create the internal model during build. I should get to this soon, but that *might solve this issue, or at least we can then look at this in detail

**Comment by jmartisk** [comment]
An internal model that can be decoupled from Jandex sounds like a good idea. I have a similar thing in SmallRye Metrics for representing annotated elements, and these model objects can be created form Jandex objects or `java.lang.reflect` objects, so it can be used at build time as well as run time.

The best option would be if `GraphQLSchema` was serializable and therefore could be constructed at build, but as that class is not under our control, that would be difficult.

**Comment by phillip-kruger** [comment]
Right, now at least the runner module works with JDK 11. I'll look at Wildfly now.

**Comment by phillip-kruger** [comment]
Hi @ribizli  and @t1 - please check now (you will have to do this from master, as this version is not yet released)

You can also see the runner (https://github.com/smallrye/smallrye-graphql/tree/master/runner) - I made a change to also run using wildfly and tested both thorntail and Wildfly using JDK 11.

You can follow the instructions in the README to test in JDK11.
I also added a sample query that also use `@Source` and that work fine.

Please let me know. Thanks

**Comment by t1** [comment]
master fails to build on my machine as well as on semaphore-ci 😢

**Comment by phillip-kruger** [comment]
@t1 Do you have an error message ?

**Comment by phillip-kruger** [comment]
@t1 - seems like there was a problem with the merge. I am looking at this now.

**Comment by phillip-kruger** [comment]
@t1 - weird. I just rebuild in semaphore, and now it's building ?!?
https://semaphoreci.com/smallrye/smallrye-graphql/branches/master/builds/53

Can you confirm on your localhost. 
Mine build fine on 8 and 11 and the Gifhub Actions build fine on 8 and 11.

I'll only close after you confirm. Thanks !

**Comment by t1** [comment]
I still have localization issues in JDK 11, but otherwise it seems to work for me.

My actual issue is still not fixed, though. I still can't use the `@Source` annotation, as when I deploy the war I get a NPE from `ReflectionDataFetcher` line 73, which is `this.declaringClass = loadClass(methodInfo.declaringClass().name().toString());` because `methodInfo.declaringClass()` return `null`... with or without Jandex. Maybe you want to take a glimpse at my [demo project](https://github.com/t1/graphql-java-experiment) (I'm currently changing it to the super heroes domain).

**Comment by phillip-kruger** [comment]
Hi @t1 - having a look at your demo now. The localization is fixed in the api (MP Spec) so make sure to use 1.0.1 that was released earlier this week.

**Comment by phillip-kruger** [comment]
@t1 What query are you doing to test the `@Source` ?

**Comment by t1** [comment]
@phillip-kruger : The query I'd like to use is this:

```
query reg {
  registration(id: "10001") {
    domain
    admin {
      person {
        firstName
        lastName
      }
    }
  }
}
```

**But it fails to even deploy.**

**Comment by phillip-kruger** [comment]
I have done a PR on the original. Basically removed the dependencies in the pom (they are pulled in via smallrye) and fixed the `Source`
![Source](https://user-images.githubusercontent.com/6836179/77150648-fe2c9b00-6a9c-11ea-8e42-aed88d4eea61.gif)

**Comment by phillip-kruger** [comment]
@t1 - let me know if we can close this. Thanks :)

**Comment by t1** [comment]
@phillip-kruger: Many thanks for your support. But it still doesn't work on wildfly. The only way I found working was using jandex... and this still fails when I have an `@Source` annotation somewhere.

When I try to build and run the `thorntail` profile, I stops with `WELD-001408: Unsatisfied dependencies for type AddressBook with qualifiers @Default` and more. How did you run your example?

**Comment by phillip-kruger** [comment]
Weird !?! This is what I ran:

cd /home/pkruger/Projects/phillip-kruger.com/graphql-java-experiment; JAVA_HOME=/opt/JDK/jdk-11 M2_HOME=/opt/maven/apache-maven-3.6.3 /opt/maven/apache-maven-3.6.3/bin/mvn -DskipTests=true -Dfile.encoding=utf-8 -Pwildfly,wildfly clean install

I do a skip test because I do not have a running wildfly, it starts with the build. But the application deploy and as in the screenshot above I can do `@Source` ??

**Comment by phillip-kruger** [comment]
@t1 I pinged you on https://gitter.im. Might be easier to try and resolve there.

**Comment by t1** [comment]
So this was my fault. It's all fixed. Sorry

**Comment by phillip-kruger** [comment]
No problem ! Closing this.

**Comment by ribizli** [comment]
@phillip-kruger sorry for late answer: I started the runner locally and everything looks fine in wildfly in JDK11.
Thanks for the fix.

**Comment by phillip-kruger** [comment]
Great news ! Thanks for letting me know !

**Comment by t1** [comment]
Are there any plans for a release, yet?

**Comment by phillip-kruger** [comment]
Hi @t1 - I hope to do a release soon. Just getting some other fixes/changes in.
