### ISSUE TITLE
io.smallrye.graphql.api.Context is not updated with new queries

### ISSUE THREAD

**Issue by giuseppeparello** [smallrye/smallrye-graphql#663]
Using inside a 1.12.0.RELEASE quarkus microservices:
 @Inject Context context;
and 
DataFetchingEnvironment dfe = context.unwrap(DataFetchingEnvironment.class);

return always the first query and not the updated one in terms of 
- dfe.getSelectionSet()
- context.getRequest()
 and so on.
Seems it has started from 1.0.19 and it is still present on 1.0.21

**Comment by phillip-kruger** [comment]
Thanks. I will have a look to see what broke this.

**Comment by t1** [comment]
We seem to have the same issue: to log all queries in a special format, we wrote a CDI interceptor with the Context injected. It looks like the context lags behind somehow. @phillip-kruger If you need more details, I could build a reproducer.

**Comment by phillip-kruger** [comment]
That would help a lot ! Thanks @t1

**Comment by t1** [comment]
I can reproduce the problem in WildFly, when I make my `@GraphQLApi` also `@Stateless`: the instance of the `Context` being injected is effectively default-scoped, i.e. it depends on the lifetime of the bean it's injected into. EJBs are pooled, so they are reused for the next request, but still with the old `Context`; so all following requests see the same `Context` as the first request (under low load).

If I kill the bean, e.g. by throwing an exception, a new one is generated with the new `Context`. I see the new query, but now it will stick to that one from now on.

If the `Context` was effectively `RequestScoped`, this should work. I looked at the implementation; the `SmallRyeContext` uses an `InheritableThreadLocal` to store the instance; I assume so that there's no dependency on CDI.

**Comment by t1** [comment]
As a workaround, we use

```java
@RequestScoped
public class GraphQlContext {
    @Inject Context graphQlContext;

    public String getQueryString() { return graphQlContext.getQuery(); }
}
```

**Comment by jmartisk** [comment]
I think the problem is that  `GraphQLProducer.getContext()` which produces the `SmallRyeContext` produces it as `@Dependent`, so if the GraphQL endpoint bean has a longer lifespan than one HTTP request, then the context will be retrieved just once and then recycled for multiple requests. 
One workaround is to use a request scoped `@GraphQLApi` endpoint, which effectively turns the `SmallRyeContext` into request-scoped too.

The solution should be to change the producer to RequestScoped.... At least I hope that there are no cases when multiple contexts are needed for one request...

**Comment by phillip-kruger** [comment]
Awesome thanks @jmartisk !

**Comment by jmartisk** [comment]
I realized the solution from my previous comment is a nonsense, because we do need multiple contexts per HTTP request (each source field has its own), therefore a RequestScoped producer would help updating the context between requests, but not between source fields that are handled within one request.

@giuseppeparello, what CDI scope is your GraphQLApi? It seems that if it's Dependent (which is the default if you don't specify any scope), a new instance is created for each source field, and therefore the context is injected correctly. At least I can't reproduce any problem in such case.
If the GraphQLApi is request scoped, the context is updated correctly between requests, but not between source fields.
If the GraphQLApi is application scoped, the context is updated neither between requests, nor between fields.

I think that to get things working when the GraphQLApi class is something else than Dependent, we would need to inject some sort of custom proxy which ALWAYS looks for the current context (on each invocation, it performs `SmallRyeContext.getContext()`).

**Comment by jmartisk** [comment]
So, in 1.0.18, it works as expected whatever the CDI scope of the `GraphQLApi` is, because the `SmallRyeContext` object is mutable and is updated every time before dispatching to application code. We then switched from a mutable object to an immutable object, and always set the ThreadLocal holding the context before dispatching to application code, but the problem is that the application obtains the `SmallRyeContext` via a [CDI producer](https://github.com/smallrye/smallrye-graphql/blob/1.1.1/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/producer/GraphQLProducer.java#L51) of a `@Dependent` scope, and so, depending on the CDI scope of the `GraphQLApi`, the injected instance might be "cached" for too long. 

As I explained earlier, this doesn't seem to be a problem if the `@GraphQLApi` is `@Dependent`. However, with other scopes, it can be a problem. (And with EJBs too, because one EJB instance is shared for multiple requests and a `@Dependent` injection point is not updated between requests)

So we can either forbid using non-dependent scopes on the GraphQL endpoints (which would probably be bad), or...
If we want to make it work with non-dependent scopes, we can either
- return back to a mutable `SmallRyeContext`, but that would be a problem for propagating the context within application code (if the application is using Mutiny, for example)
- change the [CDI producer](https://github.com/smallrye/smallrye-graphql/blob/1.1.1/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/producer/GraphQLProducer.java#L51) to return some sort of "proxy" decorator of the `SmallRyeContext` which, whenever it is called, performs `SmallRyeContext.getContext()` to obtain the actual current context and dispatch the call to it. This proxy could be application-scoped.

My preference would be the solution with the proxy decorator, unless somebody has got a better idea.

**Comment by phillip-kruger** [comment]
Let do the proxy! Thanks @jmartisk

**Comment by t1** [comment]
I like the request scoped proxy decorator. This is exactly what we did to work around the issue, only out-of-the-box :-)

**Comment by jmartisk** [comment]
Great, I'll try to implement that, I hope I didn't miss something and it will work ;)
