### ISSUE TITLE
Implement all "Serving over WebSockets" use cases

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#811]
From #304

- a separate issue to make sure we implement the "spec" : https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md
- and also look at Apollo's Sec-WebSocket-Protocol

**Comment by computerlove** [comment]
Have there been any thoughs on how this best is done?

For both client and server, should it be possible to specify the subprotocol? 
```java
@GraphQLApi(protocol="graphql-transport-ws")
```
Making all communication happen over websocket. (https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md)

```java
@GraphQLApi(protocol="graphql-ws")
```
Making query and mutation use http POST, and subscriptions websockets with protocol graphql-ws.
And 
```java
@GraphQLApi // or @GraphQLApi(protocol="subscription-as-ws") or some other naming of the current protocol
```

Similarly when specifying a client
```java
@GraphQLClientApi(protocol="graphql-transport-ws")
```

Neither protocols mentions authentication. I haven't looked at the Apollo code, but I have encountered an GraphQL API where we setup the Apollo client with
```json
{
  "connectionParams": {
      "Authorization": "Bearer some-token"
  }
}
```
or just 
```json
{
    "Authorization": "Bearer some-token"
}
```
in the headers section in GraphiQL.
`Authorization` is then contained in the `payload` of the `connection_init` message.

Right now `SecurityIdentity` is a RequestScoped bean, so not available when creating subscriptions. Not sure whether this is considered SessionScope or just have been overlooked.

**Comment by phillip-kruger** [comment]
Hi @computerlove . No thought has yet gone into this. You suggestion sounds good at first glance. To make implementation easier I would suggest a new annotation (`@Protocol`) as `@GraphQLApi` is in MicroProfile and harder to change and release.

**Comment by t1** [comment]
I think the most natural thing would be to en/disable the different protocols only for the whole service simply by just adding the dependencies you want, i.e. `smallrye-graphql-servlet` and/or `smallrye-graphql-websocket`. Is it really necessary to have some services exposed as http and others as ws?

**Comment by phillip-kruger** [comment]
There is no -websocket jar and Quarkus does not use the servlet. But agree that we can only allow this globally, and then use config to set this maybe ?

**Comment by t1** [comment]
I just assumed that there would be a `-websocket.jar` if `ws` was supported. For Quarkus we could also have two separate extensions for `http` and `ws`.

If we'd instead go for a single dependency and a single extension, a global config is actually a good idea. I'm not sure how all the artifact ids should then be named. `-servlet` doesn't make a lot of sense any more, if it also contains the websocket part, does it?

**Comment by phillip-kruger** [comment]
Yea, servlet should probably be named http with the subscription support implemented in SSE, and the we can do a seperate websocket jar. Something like that

**Comment by GavinRay97** [comment]
If it's useful, I had to write a client implementation in Java of the `graphql-transport-ws` specification
I didn't find anything that was simple + low-dependency, so I wrote two implementations:

1. Using Jakarta EE Websockets
2. Using Vert.x `HttpClient` 

https://github.com/hasura/subscriptions-examples/blob/main/java-websocket-client-demo/src/main/java/Application.java

**Comment by t1** [comment]
@GavinRay97: That may prove helpful. I just created issue #1220. Have you considered integrating this into the Typesafe SmallRye GraphQL Client yourself?

**Comment by t1** [comment]
We already do support ws on the client, so I closed that issue. @GavinRay97 : was there specific reason why this wouldn't work for you?

**Comment by GavinRay97** [comment]
> We already do support ws on the client, so I closed that issue. @GavinRay97 : was there specific reason why this wouldn't work for you?

@t1 Sure, valid question. This is probably confusing if you aren't familiar with the current spaghetti-state 🍝 of Subscriptions in GraphQL

To sum it up, there are currently two "standards" for GraphQL subscriptions, since they require a structured exchange of websocket messages due to how complicated they are.

1. Apollo's older `graphql-ws` subprotocol
    - https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md
    - This protocol has been deprecated, Apollo themselves advice to use the newer protocol
    - ![image](https://user-images.githubusercontent.com/26604994/146382914-245ca9fe-852c-4ee5-8e0a-c04259b8dbc7.png)

2. The newer `graphql-transport-ws` subprotocol that Philip mentions at the start of this article
    - https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

The implementations that you have here will not function to a `graphql-transport-ws` compliant subscription server.

For starters -- your Vert.x client will not complete a handshake with a `graphql-transport-ws` compliant server, because it has hardcoded the `subprotocols` argument to an empty list (`new ArrayList<>()`):

https://github.com/smallrye/smallrye-graphql/blob/cb91739b062d9bde6b59d46fe6f8a9da3165c8d8/client/implementation-vertx/src/main/java/io/smallrye/graphql/client/vertx/dynamic/VertxDynamicGraphQLClient.java#L212-L232

At Hasura for instance, we are stuck supporting both versions of the protocol and so our server relies on subprotocol to identify which specification of messages to exchange with that particular client:

- https://github.com/hasura/graphql-engine/blob/b167120f968cffdbb68cb9be4e9a756e7b05aedf/server/src-lib/Hasura/GraphQL/Transport/WebSocket/Protocol.hs#L41-L58

```hs
-- NOTE: the `subProtocol` is decided based on the `Sec-WebSocket-Protocol`
-- header on every request sent to the server.
data WSSubProtocol = Apollo | GraphQLWS
  deriving (Eq, Show)

-- NOTE: Please do not change them, as they're used for to identify the type of client
-- on every request that reaches the server. They are unique to each of the protocols.
showSubProtocol :: WSSubProtocol -> String
showSubProtocol subProtocol = case subProtocol of
  -- REF: https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L144
  Apollo -> "graphql-ws"
  -- REF: https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#communication
  GraphQLWS -> "graphql-transport-ws"

toWSSubProtocol :: String -> WSSubProtocol
toWSSubProtocol str = case str of
  "graphql-transport-ws" -> GraphQLWS
  _ -> Apollo
```

What I have done in the above is write a spec-compliant implementation of `graphql-transport-ws` in both Vert.x and Jakarta EE, as well as documented types for the protocol messages under a sealed interface.

I did a Github code search for `graphql-transport-ws` where `language=java` and didn't find anything that was decoupled enough to be easily used, so I wrote this implementation myself from scratch.

- https://github.com/search?l=Java&p=1&q=graphql-transport-ws&type=Code
- > (NOTE: You will see that Vert.x has a few tests for their `HttpClient` using `graphql-transport-ws`  subprotocol, but not the specification formally defined and a thorough implementation)

Hopefully even if the implementation code isn't adopted, the types can be useful for the greater Java ecosystem. I would love if SmallRye could use it, because I am a big fan of Quarkus, SmallRye, @phillip-kruger, and Red Hat.

```java
// JAVADOC COMMENT DETAILING PROTOCOL FOR EACH MESSAGE TYPE OMITTED
sealed interface GraphQLWSMessage permits
      GraphQLWSBidirectionalMessage, GraphQLWSClientToServerMessage, GraphQLWSServerToClientMessage {
    String getType();
}

sealed interface GraphQLWSBidirectionalMessage extends GraphQLWSMessage {
    record Ping(Optional<Map<String, Object>> payload) implements GraphQLWSBidirectionalMessage {}
    record Pong(Optional<Map<String, Object>> payload) implements GraphQLWSBidirectionalMessage {}
    record Complete(String id) implements GraphQLWSBidirectionalMessage {}
}

sealed interface GraphQLWSClientToServerMessage extends GraphQLWSMessage {
    record ConnectionInit(Optional<Map<String, Object>> payload) implements GraphQLWSClientToServerMessage {}
    record Subscribe(String id, SubscribePayload payload) implements GraphQLWSClientToServerMessage {
}

sealed interface GraphQLWSServerToClientMessage extends GraphQLWSMessage {
    record ConnectionAck(Optional<Map<String, Object>> payload) implements GraphQLWSServerToClientMessage {}
    record Next(String id, GraphQLExecutionResult payload) implements GraphQLWSServerToClientMessage {}
    record Error(String id, List<GraphQLError> payload) implements GraphQLWSServerToClientMessage {}
}
```

**Comment by jmartisk** [comment]
@GavinRay97 thanks for the info! The SmallRye GraphQL client is currently tested basically only against endpoints deployed through SmallRye GraphQL server-side libraries. But we'd definitely love to make it work with any reasonably spec-compliant server. I want to look into that in the near future and implement (at least) the `graphql-transport-ws` subprotocol properly. Contributions are definitely welcome too.
And we should probably add an integration test suite that runs the client against Hasura or something similar, if we figure out a way to easily run an instance for it.

**Comment by phillip-kruger** [comment]
Hi @GavinRay97 - thanks for this. We definitely need to add this to the client, and also enhance the server side to allow this. Like @jmartisk said, contributions are welcome ! On a separate note, I was trying to get hold of you on zullip. Please ping me when you can chat.

**Comment by jmartisk** [comment]
Hi @GavinRay97 , FYI I've just submitted the PR https://github.com/smallrye/smallrye-graphql/pull/1242 that adds support for both `graphql-ws` and `graphql-transport-ws` subprotocols on the client side (reviews welcome)
