### ISSUE TITLE
MP Metrics Support

### ISSUE THREAD

**Issue by andymc12** [smallrye/smallrye-graphql#91]
It would be nice to track statistics for GraphQL Query/Mutation invocations using MP Metrics.

**Comment by jmartisk** [comment]
Sounds good and I think I could try handling that.
If I get the chance, I'll do a few experiments this week and see what I can come up with

**Comment by andymc12** [comment]
Hi @jmartisk - I've got something started based on some work I did in OpenLiberty ( https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/component/MetricsInterceptor.java ).  

The main issue I'm having is that OpenLiberty puts the SmallRye implementation classes into OSGi bundles and that doesn't work too well with CDI.  That means that I may not be able to use `@Inject @RegistryType(type = Type.Vendor)` in the interceptor.  I'm thinking that I can work around that by writing the interceptor so that it could be extended,  allowing the `MetricsRegistry` to be set outside of CDI.  I'll try to post a pull request today or tomorrow with these changes.  Thanks!

**Comment by jmartisk** [comment]
Hey @andymc12 , okay, sounds good!
I would suggest looking into the possibility of not using CDI interceptors at all, there have been discussions about possibly decoupling SmallRye projects from CDI, so that would potentially save us some refactoring in the future. And while I haven't looked very deep into it, I **think** it might be possible to just add some metric instrumentation code into appropriate places within the SmallRye GraphQL code without needing the overhead of CDI interceptors.

**Comment by andymc12** [comment]
Hi @jmartisk - my preference for using CDI interceptors is to give users the choice whether they want the metrics support or not.  This way, if they run in an environment that doesn't have MP Metrics, they can just remove the metrics module - or if they do have MP Metrics and want to track GraphQL stats, then they just add the module to their app.  Vendors would have the same flexibility.  Also, MP GraphQL is tightly integrated with CDI - though not necessarily interceptors.

I suppose that we could still make Metrics support optional by using some sort of ServiceLoader pattern.  Can you take a look at my proposed change in PR #96 and let me know what you think?  If we have to, I don't think it would be too hard to refactor it to use a ServiceLoader (from the Execution servlet) to do the roughly the same thing.

Thanks!

**Comment by phillip-kruger** [comment]
Hi @jmartisk - can we merge the current module that @andymc12 added, and then you can do a PR on that to suggest the non-CDI way ?

**Comment by jmartisk** [comment]
I'll try experimenting with @andymc12 's module today and let you know, maybe it will persuade me that it's better :)

**Comment by jmartisk** [comment]
I sent a PR with a sketch of my solution: https://github.com/smallrye/smallrye-graphql/pull/111

And I realized one more reason in favor of my solution is the compatibility with Quarkus philosophy, where metrics are enabled/disabled by setting extension-specific config properties, not by adding/removing dependencies from pom. I'm not quite sure whether we would be able to programmatically include/exclude one dependency during build time based on a value of a config property - we would need something like that if we added the separate module, to prevent including the module when it's not needed, and without forcing the user to change the pom.

Anyway I guess it will be mostly @phillip-kruger 's call to choose in the end :)
I think both approaches make sense, so I won't be offended if we choose the other.

**Comment by phillip-kruger** [comment]
Hi @jmartisk - I removed the metrics stuff (for now) in the new model. I tried to add it back but got weird errors.

Would we be able to use the tests in our TCK (we can add our own tests there) rather than having a separate integration module ? 

Then, I want to see if we can do a general interceptor (somehow) and let metrics be a supplier. Or some sort of eventing.

Not sure if Quarkus can work with Proxy (in reflect) but that could be an option. Or some other way. I know that smallrye-config has recently done some interceptor work, maybe we can see what they have done ? 

Or the other option is events. So async event at the end of the call that contain the info, and listeners can do stuff with it ?

What do you think ?

Also please have a look at the new model and let me know what you think.

Thanks

**Comment by andymc12** [comment]
Another option that we could consider would be to put the metrics pre/post code in a servlet filter in the implementation-servlet project.  That moves the Metrics dependency away from the implementation and should allow users to configure it using servlet semantics.

**Comment by phillip-kruger** [comment]
Could be an option. I still would like to do something more general (so we can just plug in metrics and later maybe tracing and what ever else ?)

**Comment by jmartisk** [comment]
> Another option that we could consider would be to put the metrics pre/post code in a servlet filter in the implementation-servlet project. 

The problem there is that in the servlet layer, it's not yet computed which operation will be invoked. We 
would have to duplicate that logic to determine the operation. I don't think the servlet layer should be aware of the operation that is being invoked.

**Comment by jmartisk** [comment]
> Would we be able to use the tests in our TCK (we can add our own tests there) rather than having a separate integration module ?

I think it's reasonable to have our own integration test suite and other SmallRye projects usually have it, but if you want to move the metrics tests to the TCK, I don't mind, even though it does not logically quite fit there for me. But that's your decision :)

**Comment by jmartisk** [comment]
We could try plugging some sort of interceptor to intercept data fetchers' `get` methods, but data fetchers are not being used as CDI beans, and I don't think we can easily turn them into such, because they're being invoked from `com.graphql` code itself, so we don't have much flexibility available.

**Comment by phillip-kruger** [comment]
I was thinking more reflect proxy ? Would that work in Quarkus ?

**Comment by jmartisk** [comment]
Do you mean we would have an `InvocationHandler` that wraps the data fetcher and takes care of the metrics? I think that could potentially work, as far as I know proxies in Graal native mode work as long as the final list of implemented interfaces is known at compile time. But we'd need to double check that

**Comment by phillip-kruger** [comment]
Cool ! So maybe that is an option ?

**Comment by jmartisk** [comment]
I think it would technically work, but I'm not sure if it plays very well with your idea of plugging tracing and other stuff later, we could build a cascade of proxies, which will very soon turn ugly and probably also slow :/

**Comment by phillip-kruger** [comment]
@jmartisk  we can close this now, right ?

**Comment by jmartisk** [comment]
I hope so :)
