### ISSUE TITLE
Run typesafe client without CDI

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#967]
I have a test that uses the typesafe client api.

```java
class ClientTest {
    @Test void shouldCall() {
        var api = TypesafeGraphQLClientBuilder.newBuilder().build(Api.class);

        var hello = api.hello();

        assertEquals("Hello GraphQL", hello);
    }

    @GraphQLClientApi
    interface Api {
        @Query String hello();
    }
}
```

To configure the endpoint, I use a System Property `test.ClientTest$Api/mp-graphql/url`, but when I run it, it fails:

```
java.util.NoSuchElementException: SRGQLDC035001: URL not configured for client. Please define the property test.ClientTest$Api/mp-graphql/url or pass it to your client builder dynamically
```

This worked with 1.2.5

**Comment by t1** [comment]
I analyzed the problem: as the test runs without a CDI container, the `VertxTypesafeGraphQLClientBuilder#build` method fails when it tries to access `CDI.current()`. The resulting `IllegalStateException` is ignored, and as the `endpoint` is still `null`, it fails with the message above.

**Comment by t1** [comment]
Wouldn't it be possible to build the config with a `ConfigMapping` instead of CDI?

**Comment by jmartisk** [comment]
If we switch the `GraphQLClientsConfiguration` class away from CDI, as it is now an application-scoped bean; how will we make sure we have one instance of it per application (in multi-deployment environments)? Should we store its instances in a map that is keyed by the application's context class loader? (any better idea how to emulate an application-scoped bean without CDI?)
And instead of injecting, it will be retrieved by a static method that performs a lookup in the map?
I suppose this could work, even though it will be a bit more code than we have now

**Comment by t1** [comment]
Maybe I'm naïve, but isn't this a problem that SR Config should be able to solve?

**Comment by jmartisk** [comment]
SR Config can solve different raw configuration properties for applications, but not storing the "processed" config that we do in `GraphQLClientConfiguration` object where we want to store everything - for the future, I'm also planning to merge stuff parsed from annotations into it (so that we don't have to do a ton of reflection on every request at runtime for re-parsing the annotations)

**Comment by jmartisk** [comment]
Another reason for using a dedicated class instead of just reading raw config properties is that Quarkus has its own specific configuration object (https://github.com/quarkusio/quarkus/blob/2.1.1.Final/extensions/smallrye-graphql-client/runtime/src/main/java/io/quarkus/smallrye/graphql/client/runtime/GraphQLClientConfig.java) that gets transformed into a `GraphQLClientConfiguration`, so that SmallRye doesn't need to be able to parse Quarkus-specific properties.

**Comment by t1** [comment]
Okay, but the current dependency on CDI is not ideal either, is it? We found a workaround for our current JUnit use-case: we configure the `endpoint` instead of the prefix, which is okay for the tests we have now, but we won't be able to configure headers in this way... or other config options that may come in the future.

**Comment by jmartisk** [comment]
Yeah requiring CDI is probably unnecessary. We've been using the approach that I described in several other places already - instead of an application scoped bean, you store instances in a static map keyed by the TCCL. There's one more caveat to it, you can't use TCCL as the key in Quarkus if you populate the map at build time, because in native mode, the TCCL instance will be different at runtime... so Quarkus would simply use a `null` key instead of the TCCL (there's only one deployment, so it is sufficient).

I can try implementing this approach for the config, but I might not be able to finish it before my 2 weeks PTO.

**Comment by t1** [comment]
We can live with the workaround for now, so this is not top priority.

I have the feeling that this should be solved by MP Config instead of repeating the same approach in several places, don't you think?

**Comment by t1** [comment]
I'm just triggered to do my philosophic thinking here. Without digging deeper to see how far we can get and create a PR, I'm just talking ;-) Don't take my thoughts too seriously.

I'm not arguing against using CDI when it's available. CDI is great and we should use it! Couldn't even the `SmallRyeContext` be `@RequestScoped` and inject the `Schema` which would be `@ApplicationScoped`? Can't we directly inject all configuration into our central `GraphQLClientConfiguration` class that can also hold directly additional logic? Let CDI do the hard work.

Only when the `TypesafeGraphQLClientBuilder` is used in an environment without CDI, we need to build all these objects by hand. But then there can't be multiple applications etc., so we actually don't need the really hard stuff. This would be quite easy if we could pull the configuration from MP Config without depending on CDI. I don't understand why the `ConfigMapping` annotation only works with CDI. Otherwise we could use it for our `GraphQLClientConfiguration`. I think this is an issue for MP Config. I understand that we may have to work around that limitation. And I have currently no idea how this would work best. It's just a gut feeling.
